"""LaTeX (TikZ) figure + wide main table, generated from analysis/counts.csv.

  analysis/figure_strength.tex      Figure: per-attack ASR across the 8 targets (primary judge, any-turn)
  analysis/results_table_wide.tex   Table: 8 targets x 5 attacks x 3 judges (any-turn), top attack bold

Usage: python make_figures.py
"""
import csv

from build_tables import METHOD_NAMES, METHODS, TARGETS

JUDGES = [("qwen7b", "Qwen2.5-7B (primary)"), ("qwen72b", "Qwen2.5-72B"), ("llamaguard", "Llama-Guard-3")]
SHORT = {"internvl25_8b": "InternVL-8B", "internvl25_26b": "InternVL-26B", "qwen25vl7b": "Qwen-VL-7B",
         "qwen25vl_32b": "Qwen-VL-32B", "llava_ov_7b": "LLaVA-OV-7B", "phi35_vision": "Phi-3.5-V",
         "minicpm_v26": "MiniCPM-V", "pixtral_12b": "Pixtral-12B"}
ABBR = {"figstep": "Fig", "pair": "PAIR", "crescendo": "Cres", "strata_image": "S-Img", "strata_pdf": "S-PDF"}


def load():
    c = {(r["method"], r["target"], r["judge"]): r for r in csv.DictReader(open("analysis/counts.csv"))}
    return lambda m, t, j: 100 * int(c[(m, t, j)]["k_any"]) / int(c[(m, t, j)]["n"])


def figure(A):
    order = sorted(METHODS, key=lambda m: -sum(A(m, t, "qwen7b") for t, _ in TARGETS))
    u, row, left, xmax = 0.25, 0.62, 0.0, 18  # cm per pp, cm per row
    L = [r"% Generated by make_figures.py from analysis/counts.csv -- do not edit by hand.",
         r"\begin{figure}[t]", r"\centering",
         r"\definecolor{dotblue}{HTML}{2A78D6}\definecolor{gridc}{HTML}{E1E0D9}"
         r"\definecolor{mutedc}{HTML}{898781}\definecolor{inkc}{HTML}{52514E}",
         r"\begin{tikzpicture}[font=\scriptsize]"]
    top = row * (len(order) - 1)
    for x in range(0, xmax + 1, 3):  # recessive vertical grid + tick labels
        L.append(rf"\draw[gridc, line width=0.3pt] ({x * u:.3f},-0.35) -- ({x * u:.3f},{top + 0.35:.3f});")
        L.append(rf"\node[mutedc, below] at ({x * u:.3f},-0.35) {{{x}}};")
    L.append(rf"\node[mutedc] at ({xmax * u / 2:.3f},-0.95) {{ASR (\%), primary judge, any-turn}};")
    for i, m in enumerate(order):
        y = top - i * row
        vals = [(A(m, t, "qwen7b"), t) for t, _ in TARGETS]
        lo, hi = min(v for v, _ in vals), max(v for v, _ in vals)
        mean = sum(v for v, _ in vals) / len(vals)
        L.append(rf"\node[anchor=east, text=black] at (-0.15,{y:.3f}) {{\footnotesize {METHOD_NAMES[m]}}};")
        L.append(rf"\draw[mutedc, line width=0.6pt] ({lo * u:.3f},{y:.3f}) -- ({hi * u:.3f},{y:.3f});")
        for k, (v, t) in enumerate(sorted(vals)):  # small deterministic vertical offset separates near-ties
            dy = (-0.07, 0.07)[k % 2]
            L.append(rf"\fill[dotblue, draw=white, line width=0.5pt] ({v * u:.3f},{y + dy:.3f}) circle (2.1pt);")
        L.append(rf"\draw[black, line width=1.2pt] ({mean * u:.3f},{y - 0.2:.3f}) -- ({mean * u:.3f},{y + 0.2:.3f});")
        L.append(rf"\node[inkc, anchor=west] at ({hi * u + 0.12:.3f},{y:.3f}) {{{mean:.1f}}};")
        if m == order[0]:  # name the extremes of the widest row only
            vmin = min(vals)
            vmax = max(vals)
            L.append(rf"\node[inkc, above] at ({vmin[0] * u:.3f},{y + 0.12:.3f}) {{{SHORT[vmin[1]]}}};")
            L.append(rf"\node[inkc, above] at ({vmax[0] * u:.3f},{y + 0.12:.3f}) {{{SHORT[vmax[1]]}}};")
    L += [r"\end{tikzpicture}",
          r"\caption{ASR of each attack on the eight targets under the primary judge (any-turn). "
          r"Dots: targets; black tick and number: mean over targets; grey line: range. FigStep has the highest mean "
          r"and by far the widest range. \strata{} contributes two of the five attacks, so it enters the "
          r"grand mean and the target susceptibilities twice.}",
          r"\label{fig:strength}", r"\end{figure}"]
    return "\n".join(L) + "\n"


def table(A):
    nm = len(METHODS)
    cols = "l" + ("r" * nm) * len(JUDGES)
    groups = " ".join(rf"\cmidrule(lr){{{2 + k * nm}-{1 + (k + 1) * nm}}}" for k in range(len(JUDGES)))
    L = [r"% Generated by make_figures.py from analysis/counts.csv -- do not edit by hand.",
         r"\begin{table*}[t]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         rf"\resizebox{{\textwidth}}{{!}}{{%", rf"\begin{{tabular}}{{{cols}}}", r"\toprule",
         " & " + " & ".join(rf"\multicolumn{{{nm}}}{{c}}{{\textbf{{{name}}}}}" for _, name in JUDGES) + r" \\",
         groups,
         r"\textbf{Target} & " + " & ".join(ABBR[m] for _ in JUDGES for m in METHODS) + r" \\", r"\midrule"]
    for t, name in TARGETS:
        cells = []
        for j, _ in JUDGES:
            v = [A(m, t, j) for m in METHODS]
            best = max(v)
            cells += [rf"\textbf{{{x:.1f}}}" if x == best else f"{x:.1f}" for x in v]
        L.append(f"{name} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    means = [sum(A(m, t, j) for t, _ in TARGETS) / len(TARGETS) for j, _ in JUDGES for m in METHODS]
    L.append(r"\textit{Mean} & " + " & ".join(rf"\textit{{{x:.1f}}}" for x in means) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}}",
          r"\caption{Attack success rate (\%, any-turn: a request succeeds if any turn scores $\geq\tau{=}8$) "
          r"on all eight targets under the three judges; the highest ASR per target and judge is in bold. "
          r"Fig = FigStep, Cres = Crescendo, S-Img/S-PDF = \strata{}-Image/-PDF. FigStep, PAIR and \strata{} pool "
          r"three seeds ($n{\leq}600$) on the four original targets and one seed ($n{=}200$) on the others; "
          r"Crescendo uses one seed except on Qwen2.5-VL-32B (three). \strata{} is evaluated on its first two turns. "
          r"Per-cell $n$ and Wilson 95\% intervals are in Appendix~\ref{app:full_grid}.}",
          r"\label{tab:full_results}", r"\end{table*}"]
    return "\n".join(L) + "\n"


def reversal(A):
    """Figure 1 candidate: FigStep vs PAIR on InternVL2.5-8B and Qwen2.5-VL-7B, one panel per judge."""
    from scipy import stats

    from robustness import request_records

    t1, t2 = "internvl25_8b", "qwen25vl7b"

    def mcnemar_p(R, t):
        a = {(r["seed"], r["rid"]): r["max_score"] >= 8 for r in R[("figstep", t)]}
        b = {(r["seed"], r["rid"]): r["max_score"] >= 8 for r in R[("pair", t)]}
        k = a.keys() & b.keys()
        x = sum(a[i] and not b[i] for i in k)
        y = sum(b[i] and not a[i] for i in k)
        return stats.binomtest(x, x + y, 0.5).pvalue if x + y else 1.0

    nice = [4, 6, 8, 10, 12, 16, 20, 30, 40, 60, 80, 100]
    W, H, x1, x2, gap = 1.95, 2.6, 0.35, 1.6, 0.6
    L = [r"% Generated by make_figures.py from the per-turn judge files -- do not edit by hand.",
         r"\begin{figure}[t]", r"\centering",
         r"\definecolor{figc}{HTML}{2A78D6}\definecolor{pairc}{HTML}{EB6834}\definecolor{gridc}{HTML}{E1E0D9}"
         r"\definecolor{mutedc}{HTML}{898781}\definecolor{inkc}{HTML}{52514E}",
         r"\begin{tikzpicture}[font=\scriptsize]"]
    for k, (j, name) in enumerate([("qwen7b", "Qwen2.5-7B"), ("qwen72b", "Qwen2.5-72B"), ("llamaguard", "Llama-Guard-3")]):
        R = request_records(j)
        ox = k * (W + gap)
        vals = {m: (A(m, t1, j), A(m, t2, j)) for m in ("figstep", "pair")}
        ymax = next(v for v in nice if v >= 1.08 * max(max(p) for p in vals.values()))
        s = H / ymax
        for tv in (0, ymax // 2, ymax):
            L.append(rf"\draw[gridc, line width=0.3pt] ({ox:.3f},{tv * s:.3f}) -- ({ox + W:.3f},{tv * s:.3f});")
            L.append(rf"\node[mutedc, anchor=east, font=\tiny] at ({ox - 0.03:.3f},{tv * s:.3f}) {{{tv}}};")
        L.append(rf"\node[black, font=\scriptsize\bfseries] at ({ox + W / 2:.3f},{H + 0.3:.3f}) {{{name}}};")
        for x, lab in ((x1, r"InternVL\\8B"), (x2, r"Qwen-VL\\7B")):
            L.append(rf"\node[inkc, align=center, font=\tiny, below] at ({ox + x:.3f},-0.05) {{{lab}}};")
        for m, col, mark in (("pair", "pairc", "rectangle"), ("figstep", "figc", "circle")):
            a, b = vals[m]
            L.append(rf"\draw[{col}, line width=1.1pt] ({ox + x1:.3f},{a * s:.3f}) -- ({ox + x2:.3f},{b * s:.3f});")
            for x, v in ((x1, a), (x2, b)):
                if mark == "circle":
                    L.append(rf"\fill[{col}, draw=white, line width=0.5pt] ({ox + x:.3f},{v * s:.3f}) circle (2.2pt);")
                else:
                    L.append(rf"\fill[{col}, draw=white, line width=0.5pt] ({ox + x - 0.075:.3f},{v * s - 0.075:.3f}) "
                             rf"rectangle ({ox + x + 0.075:.3f},{v * s + 0.075:.3f});")
        for x, t in ((x1, t1), (x2, t2)):  # significance of the lead on each side
            p = mcnemar_p(R, t)
            top = max(vals["figstep"][0 if t == t1 else 1], vals["pair"][0 if t == t1 else 1])
            mark = "$\\ast$" if p < 0.05 else "n.s."
            L.append(rf"\node[inkc, font=\tiny, above] at ({ox + x:.3f},{top * s + 0.07:.3f}) {{{mark}}};")
    ly = -0.95
    L += [rf"\draw[figc, line width=1.1pt] (0.9,{ly}) -- (1.3,{ly}); \fill[figc, draw=white, line width=0.5pt] (1.1,{ly}) circle (2.2pt);",
          rf"\node[black, anchor=west] at (1.35,{ly}) {{FigStep}};",
          rf"\draw[pairc, line width=1.1pt] (2.75,{ly}) -- (3.15,{ly}); \fill[pairc, draw=white, line width=0.5pt] (2.875,{ly - 0.075}) rectangle (3.025,{ly + 0.075});",
          rf"\node[black, anchor=west] at (3.2,{ly}) {{PAIR}};",
          rf"\node[inkc, anchor=west] at (4.3,{ly}) {{$\ast$ paired $p{{<}}0.05$}};",
          r"\end{tikzpicture}",
          r"\caption{FigStep leads PAIR on InternVL2.5-8B and trails it on Qwen2.5-VL-7B under all three judges "
          r"(ASR \%, any-turn; each panel has its own scale). $\ast$: the leading attack's advantage on that target "
          r"is significant (paired McNemar, $p{<}0.05$); n.s.: not significant.}",
          r"\label{fig:reversal}", r"\end{figure}"]
    return "\n".join(L) + "\n"


def main():
    A = load()
    open("analysis/figure_strength.tex", "w", encoding="utf-8").write(figure(A))
    open("analysis/results_table_wide.tex", "w", encoding="utf-8").write(table(A))
    open("analysis/figure_reversal.tex", "w", encoding="utf-8").write(reversal(A))
    print("wrote analysis/figure_strength.tex, analysis/results_table_wide.tex, analysis/figure_reversal.tex")


if __name__ == "__main__":
    main()
