"""Candidate tables/figures for the camera-ready main text (for review; not \\input by the paper).

Writes analysis/variants/*.tex:
  t1_a_stretch      Table 1 with more row spacing
  t1_b_grouped      + family grouping gaps and wider gaps between judge blocks
  t1_c_zebra        + light alternate-row shading (needs \\usepackage{colortbl})
  t1_d_natural      no resizebox: \\small, spaced, shrinks only if too wide
  t2_a_compact      Table 2 without resizebox, 1-dp, two-line headers
  t2_b_alpha        Table 2 with alpha column and an inline range plot
  f_gamma_col       gamma heatmap, primary judge (single column)
  f_gamma_3judge    gamma heatmaps under all three judges (full width)
  f_top1_judges     top-ranked attack per target under each judge (single column)
  f_waterfall       FigStep decomposition on InternVL2.5-8B vs Qwen2.5-VL-7B (single column)
  f_judge_shift     mean ASR per attack under Qwen-7B vs Qwen-72B, log scale (single column)
  f_cres_turns      Crescendo cumulative ASR by turn, k=6 vs k=10 (single column)

Usage: python make_variants.py
"""
import os

import numpy as np

from appendix_latex import JORDER, JN, SHORT, kn, TAU, cell_outcomes, load_jsonl, ORIG4, NAME
from build_tables import METHODS, TARGETS
from decompose import decompose

OUT = "analysis/variants"
T1 = open("analysis/results_table_wide.tex", encoding="utf-8").read()
ST = r"\strata{}"
MSHORT = {"figstep": "FigStep", "pair": "PAIR", "crescendo": "Crescendo",
          "strata_image": ST + "-Img", "strata_pdf": ST + "-PDF"}
TSHORT = {"figstep": "Fig", "pair": "PAIR", "crescendo": "Cres", "strata_image": "S-Img", "strata_pdf": "S-PDF"}
MCOL = {"crescendo": "mCres", "figstep": "mFig", "pair": "mPair", "strata_image": "mSImg", "strata_pdf": "mSPdf"}
COLDEFS = (r"\definecolor{mCres}{RGB}{160,160,160}\definecolor{mFig}{RGB}{31,119,180}"
           r"\definecolor{mPair}{RGB}{255,127,14}\definecolor{mSImg}{RGB}{44,160,44}"
           r"\definecolor{mSPdf}{RGB}{214,39,40}\definecolor{posc}{HTML}{018571}"
           r"\definecolor{negc}{HTML}{A6611A}\definecolor{gridc}{HTML}{E1E0D9}"
           r"\definecolor{inkc}{HTML}{52514E}\definecolor{serA}{HTML}{2A78D6}\definecolor{serB}{HTML}{EB6834}")


def write(name, text):
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, name + ".tex"), "w", encoding="utf-8").write(
        "% Generated by make_variants.py -- candidate for review, not yet in the paper.\n" + text)


def matrix(j):
    k = np.array([[kn(m, t, j)[0] for t, _ in TARGETS] for m in METHODS], float)
    n = np.array([[kn(m, t, j)[1] for t, _ in TARGETS] for m in METHODS], float)
    return k, n, 100 * k / n


# ---------------------------------------------------------------- Table 1
def table1():
    rows = [ln for ln in T1.splitlines() if ln.split(" & ")[0] in dict(TARGETS).values()]
    stretch = lambda s, v: s.replace(r"\setlength{\tabcolsep}{3pt}",
                                     r"\setlength{\tabcolsep}{3pt}" + "\n" + rf"\renewcommand{{\arraystretch}}{{{v}}}")
    write("t1_a_stretch", stretch(T1, 1.3))

    b = stretch(T1, 1.2).replace(r"{lrrrrrrrrrrrrrrr}", r"{l rrrrr@{\hspace{12pt}}rrrrr@{\hspace{12pt}}rrrrr}")
    for name in ("InternVL2.5-26B", "Qwen2.5-VL-32B"):
        row = next(r for r in rows if r.startswith(name))
        b = b.replace(row, row + r" \addlinespace[4pt]")
    write("t1_b_grouped", b)
    e = b
    for i, r in enumerate(rows):
        if i % 2 == 1:
            e = e.replace(r, r"\rowcolor{black!5}" + r)
    write("t1_e_grouped_zebra", "% needs \\usepackage{colortbl} in the preamble\n" + e)

    c = stretch(T1, 1.25)
    for i, r in enumerate(rows):
        if i % 2 == 1:
            c = c.replace(r, r"\rowcolor{black!5}" + r)
    write("t1_c_zebra", "% needs \\usepackage{colortbl} in the preamble\n" + c)

    d = (T1.replace(r"\footnotesize", r"\small")
           .replace(r"\setlength{\tabcolsep}{3pt}", r"\setlength{\tabcolsep}{3.5pt}" + "\n" + r"\renewcommand{\arraystretch}{1.3}")
           .replace(r"\resizebox{\textwidth}{!}{%", r"\begin{adjustbox}{max width=\textwidth}")
           .replace(r"\end{tabular}}", r"\end{tabular}" + "\n" + r"\end{adjustbox}"))
    write("t1_d_natural", d)


# ---------------------------------------------------------------- Table 2
def table2():
    _, _, A = matrix("qwen7b")
    mu, alpha, _, _ = decompose(A)
    order = np.argsort(-A.mean(1))
    top = [set(np.flatnonzero(np.isclose(A[:, c], A[:, c].max()))) for c in range(A.shape[1])]
    cap_tail = (rf"under the primary judge (grand mean $\mu = {mu:.1f}\%$). SD: standard deviation across the eight "
                r"targets. Top-ranked: number of targets on which the attack has the highest ASR (MiniCPM-V-2.6 is tied "
                r"between FigStep and Crescendo).")
    two = lambda a, b: rf"\begin{{tabular}}[b]{{@{{}}c@{{}}}}{a}\\{b}\end{{tabular}}"

    rows = []
    for i in order:
        m = METHODS[i]
        rows.append(f"{MSHORT[m]} & {A[i].mean():.1f} & {A[i].std(ddof=1):.1f} & {A[i].min():.1f}--{A[i].max():.1f} & "
                    f"{sum(i in s for s in top)}/8" + r" \\")
    write("t2_a_compact", "\n".join([
        r"\begin{table}[t]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{5pt}",
        r"\renewcommand{\arraystretch}{1.15}", r"\begin{tabular}{lcccc}", r"\toprule",
        r"\textbf{Attack} & " + " & ".join(two(*h) for h in [(r"\textbf{Mean}", r"\textbf{ASR (\%)}"),
                                                             (r"\textbf{SD}", r"\textbf{(pp)}"),
                                                             (r"\textbf{Range}", r"\textbf{(\%)}"),
                                                             (r"\textbf{Top-}", r"\textbf{ranked}")]) + r" \\",
        r"\midrule", *rows, r"\bottomrule", r"\end{tabular}",
        r"\caption{Mean ASR and cross-target spread of each attack over the eight targets " + cap_tail + "}",
        r"\label{tab:decomp_strength}", r"\end{table}", ""]))

    # with alpha and an inline range plot (0-18 %, 2.2 cm)
    W, X = 1.5, 18.0
    x = lambda v: f"{W * v / X:.3f}"
    rows = []
    for i in order:
        m, a = METHODS[i], A[i]
        pts = "".join(rf"\fill[black!45] ({x(v)},0) circle (0.6pt);" for v in a)
        plot = (rf"\begin{{tikzpicture}}[baseline=-0.6ex]\draw[gridc, line width=0.4pt] (0,0) -- ({W},0);"
                rf"\draw[inkc, line width=1.2pt] ({x(a.min())},0) -- ({x(a.max())},0);{pts}"
                rf"\draw[black, fill=white, line width=0.5pt] ({x(a.mean())},0) circle (1.5pt);\end{{tikzpicture}}")
        rows.append(f"{MSHORT[m]} & {a.mean():.1f} & {f'{alpha[i]:+.1f}'.replace('-', '$-$')} & {a.std(ddof=1):.1f} & {sum(i in s for s in top)}/8 & "
                    + plot + r" \\")
    axis = (rf"\begin{{tikzpicture}}[baseline=0pt]" + "".join(
        rf"\node[font=\tiny, inner sep=0pt, anchor=base] at ({x(v)},0) {{{v}}};" for v in (0, 9, 18))
        + r"\end{tikzpicture}")
    write("t2_b_alpha", "\n".join([
        r"\begin{table}[t]", r"\centering", r"\footnotesize", COLDEFS, r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.25}", r"\begin{tabular}{lccccc}", r"\toprule",
        r"\textbf{Attack} & " + " & ".join(two(*h) for h in [(r"\textbf{Mean}", r"\textbf{(\%)}"),
                                                             (r"$\boldsymbol{\alpha_m}$", r"\textbf{(pp)}"),
                                                             (r"\textbf{SD}", r"\textbf{(pp)}"),
                                                             (r"\textbf{Top-}", r"\textbf{ranked}"),
                                                             (r"\textbf{Per target}", axis)]) + r" \\",
        r"\midrule", *rows, r"\bottomrule", r"\end{tabular}",
        r"\caption{General strength and cross-target spread of each attack " + cap_tail.replace("(grand", r"(grand")
        + r" $\alpha_m$ = Mean $-$ $\mu$. Right: ASR on each of the eight targets (grey dots), range (bar) and mean (open circle).}",
        r"\label{tab:decomp_strength}", r"\end{table}", ""]))


# ---------------------------------------------------------------- gamma heatmaps
def gamma_sig(j):
    k, n, A = matrix(j)
    mu, alpha, beta, g = decompose(A)
    rng = np.random.default_rng(0)  # same seed as appendix_latex.gamma()
    boot = np.array([decompose(100 * rng.binomial(n.astype(int), k / n) / n)[3] for _ in range(2000)])
    lo, hi = np.percentile(boot, [2.5, 97.5], axis=0)
    return g, (lo > 0) | (hi < 0)


def cell(v, s, gmax, x, y, w, h, font):
    """One heatmap cell: diverging fill (teal +, brown -), value, * if the interval excludes zero."""
    p = int(round(85 * min(1, abs(v) / gmax)))
    col = ("posc" if v > 0 else "negc") + f"!{p}!white"
    ink = "white" if p > 55 else "black"
    txt = f"{v:+.1f}".replace("-", "$-$") + ("$^{*}$" if s else "")
    return (rf"\fill[{col}] ({x:.2f},{y:.2f}) rectangle ++({w - 0.03:.2f},{h - 0.03:.2f});" + "\n"
            + rf"\node[font={font}, text={ink}] at ({x + w / 2 - 0.015:.3f},{y + h / 2 - 0.015:.3f}) {{{txt}}};")


def heat_panel(j, x0, labels, cw=0.95, ch=0.42, title=None,
               vfont=r"\tiny", hfont=r"\tiny", lfont=r"\scriptsize", tfont=r"\scriptsize\bfseries"):
    """Targets as rows, attacks as columns."""
    g, sig = gamma_sig(j)
    gmax = np.abs(g).max()
    out = []
    if title:
        out.append(rf"\node[font={tfont}, anchor=south] at ({x0 + cw * 2.5:.2f},{ch * 8 + 0.45:.2f}) {{{title}}};")
    for i, m in enumerate(METHODS):
        out.append(rf"\node[font={hfont}, anchor=south, inner sep=1pt] at ({x0 + cw * (i + 0.5):.2f},{ch * 8 + 0.03:.2f}) "
                   rf"{{{TSHORT[m]}}};")
    for c, (t, _) in enumerate(TARGETS):
        y = ch * (7 - c)
        if labels:
            out.append(rf"\node[font={lfont}, anchor=east] at ({x0 - 0.06:.2f},{y + ch / 2:.2f}) {{{SHORT[t]}}};")
        for i in range(len(METHODS)):
            out.append(cell(g[i, c], sig[i, c], gmax, x0 + cw * i, y, cw, ch, vfont))
    return "\n".join(out)


def heat_wide(j, cw=1.62, ch=0.56):
    """Attacks as rows, targets as columns (for a full-width single-judge figure)."""
    g, sig = gamma_sig(j)
    gmax = np.abs(g).max()
    M = len(METHODS)
    out = []
    two = {"internvl25_8b": r"InternVL2.5\\8B", "internvl25_26b": r"InternVL2.5\\26B", "qwen25vl7b": r"Qwen2.5-VL\\7B",
           "qwen25vl_32b": r"Qwen2.5-VL\\32B", "llava_ov_7b": r"LLaVA-OV\\7B", "phi35_vision": r"Phi-3.5\\Vision",
           "minicpm_v26": r"MiniCPM-V\\2.6", "pixtral_12b": r"Pixtral\\12B"}
    for c, (t, _) in enumerate(TARGETS):
        out.append(rf"\node[font=\scriptsize, anchor=south, inner sep=1pt, align=center] at "
                   rf"({cw * (c + 0.5):.2f},{ch * M + 0.03:.2f}) {{{two[t]}}};")
    for i, m in enumerate(METHODS):
        y = ch * (M - 1 - i)
        out.append(rf"\node[font=\footnotesize, anchor=east] at (-0.06,{y + ch / 2:.2f}) {{{MSHORT[m]}}};")
        for c in range(len(TARGETS)):
            out.append(cell(g[i, c], sig[i, c], gmax, cw * c, y, cw, ch, r"\footnotesize"))
    return "\n".join(out)


def gamma_figs():
    cap = (r"Values are percentage points; $^{*}$: 95\% bootstrap interval excludes zero. Teal: the attack does better on "
           r"that target than its general strength and the target's susceptibility predict; brown: worse. Each row and "
           r"column sums to zero.")
    write("f_gamma_col", "\n".join([
        r"\begin{figure}[t]", r"\centering", COLDEFS, r"\begin{tikzpicture}", heat_panel("qwen7b", 0, True),
        r"\end{tikzpicture}",
        r"\caption{Target-specific fit $\gamma_{mt}$ under the primary judge. " + cap + r" FigStep's row carries the "
        r"largest values: its fit is positive on both InternVL models and Pixtral-12B and negative on the other five "
        r"targets.}",
        r"\label{fig:gamma}", r"\end{figure}", ""]))
    cw = 0.82
    panels = [heat_panel(j, x0, x0 == 0, cw=cw, title=JN[j]) for j, x0 in zip(JORDER, (0, 4.45, 8.9))]
    write("f_gamma_3judge", "\n".join([
        r"\begin{figure*}[t]", r"\centering", COLDEFS, r"\begin{tikzpicture}", *panels, r"\end{tikzpicture}",
        r"\caption{Target-specific fit $\gamma_{mt}$ under each judge. Colour is scaled separately per judge, since "
        r"ASR levels differ greatly between judges. " + cap + "}",
        r"\label{fig:gamma}", r"\end{figure*}", ""]))

    # larger versions for the main text
    figrow = (r"The FigStep row carries the largest values in every panel: its fit is positive on both InternVL models "
              r"and Pixtral-12B and negative on both Qwen models and MiniCPM-V under all three judges.")
    big = [heat_panel(j, x0, x0 == 0, cw=0.87, ch=0.5, title=JN[j], vfont=r"\scriptsize", hfont=r"\scriptsize",
                      lfont=r"\footnotesize", tfont=r"\footnotesize\bfseries")
           for j, x0 in zip(JORDER, (0, 4.72, 9.44))]
    write("f_gamma_3judge_big", "\n".join([
        r"\begin{figure*}[t]", r"\centering", COLDEFS, r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tikzpicture}", *big, r"\end{tikzpicture}", r"\end{adjustbox}",
        r"\caption{Target-specific fit $\gamma_{mt}$ (percentage points) under each judge. Teal: the attack does "
        r"better on that target than its general strength and the target's susceptibility predict; brown: worse; "
        r"$^{*}$: 95\% bootstrap interval excludes zero. Colour is scaled separately per judge, since ASR levels "
        r"differ greatly between judges; compare signs, not shades, across panels. " + figrow + r" Each row and "
        r"column sums to zero.}",
        r"\label{fig:gamma}", r"\end{figure*}", ""]))
    write("f_gamma_wide_primary", "\n".join([
        r"\begin{figure*}[t]", r"\centering", COLDEFS, r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tikzpicture}", heat_wide("qwen7b"), r"\end{tikzpicture}", r"\end{adjustbox}",
        r"\caption{Target-specific fit $\gamma_{mt}$ (percentage points) under the primary judge. Teal: the attack "
        r"does better on that target than its general strength and the target's susceptibility predict; brown: "
        r"worse; $^{*}$: 95\% bootstrap interval excludes zero. FigStep's row carries the largest values: its fit "
        r"is positive on both InternVL models and Pixtral-12B and negative on the other five targets. Each row and "
        r"column sums to zero; the matrices under the other judges are in Appendix~\ref{app:gamma}.}",
        r"\label{fig:gamma}", r"\end{figure*}", ""]))


# ---------------------------------------------------------------- top-1 per judge
def top1_table():
    tops = {}
    for j in JORDER:
        _, _, A = matrix(j)
        tops[j] = [[METHODS[i] for i in np.flatnonzero(np.isclose(A[:, c], A[:, c].max()))] for c in range(len(TARGETS))]
    chip = lambda m: rf"\tikz[baseline=-0.6ex]\fill[{MCOL[m]}] (0,-0.08) rectangle (0.16,0.08);\,{TSHORT[m]}"
    rows = []
    for c, (t, name) in enumerate(TARGETS):
        cells = []
        for j in JORDER:
            s = " = ".join(chip(m) for m in tops[j][c])
            if j != "qwen7b" and tops[j][c] != tops["qwen7b"][c]:
                s += r"$^{\dagger}$"
            cells.append(s)
        rows.append(f"{name} & " + " & ".join(cells) + r" \\")
    write("f_top1_judges", "\n".join([
        r"\begin{table}[t]", r"\centering", r"\footnotesize", COLDEFS, r"\setlength{\tabcolsep}{5pt}",
        r"\renewcommand{\arraystretch}{1.2}",
        r"\begin{adjustbox}{max width=\columnwidth}", r"\begin{tabular}{llll}", r"\toprule",
        r"\textbf{Target} & \textbf{Qwen2.5-7B} & \textbf{Qwen2.5-72B} & \textbf{Llama-Guard-3} \\", r"\midrule",
        *rows, r"\bottomrule", r"\end{tabular}", r"\end{adjustbox}",
        r"\caption{Top-ranked attack on each target under each judge (any-turn ASR); ``='' marks a tie. "
        r"$^{\dagger}$: differs from the primary judge.}",
        r"\label{tab:top1_judges}", r"\end{table}", ""]))


# ---------------------------------------------------------------- waterfall
def waterfall():
    _, _, A = matrix("qwen7b")
    mu, alpha, beta, g = decompose(A)
    i = METHODS.index("figstep")
    tgt = [("internvl25_8b", "InternVL2.5-8B"), ("qwen25vl7b", "Qwen2.5-VL-7B")]
    ys, bw, gap = 0.2, 0.42, 0.14   # cm per pp, bar width, gap
    out = [r"\begin{tikzpicture}[font=\scriptsize]"]
    top = 14
    for p, (t, name) in enumerate(tgt):
        c = [k for k, _ in TARGETS].index(t)
        comps = [(r"$\mu$", mu, "black!35"), (r"$\alpha$", alpha[i], "mFig!55"), (r"$\beta$", beta[c], "black!20"),
                 (r"$\gamma$", g[i, c], "posc" if g[i, c] > 0 else "negc")]
        x0 = p * (5 * (bw + gap) + 0.7)
        run = 0.0
        for q, (lab, v, col) in enumerate(comps):
            x = x0 + q * (bw + gap)
            lo, hi = sorted((run, run + v))
            out.append(rf"\fill[{col}] ({x:.2f},{lo * ys:.3f}) rectangle ++({bw:.2f},{(hi - lo) * ys:.3f});")
            if q:
                out.append(rf"\draw[black!40, densely dotted] ({x - gap:.2f},{run * ys:.3f}) -- ({x:.2f},{run * ys:.3f});")
            vs = f"{v:+.1f}".replace("-", "$-$")
            out.append(rf"\node[anchor=south, inner sep=1pt] at ({x + bw / 2:.2f},{hi * ys:.3f}) {{{vs}}};"
                       if q else rf"\node[anchor=south, inner sep=1pt] at ({x + bw / 2:.2f},{hi * ys:.3f}) {{{v:.1f}}};")
            out.append(rf"\node[anchor=north, inner sep=2pt] at ({x + bw / 2:.2f},0) {{{lab}}};")
            run += v
        x = x0 + 4 * (bw + gap)
        out.append(rf"\draw[black!40, densely dotted] ({x - gap:.2f},{run * ys:.3f}) -- ({x:.2f},{run * ys:.3f});")
        out.append(rf"\fill[mFig] ({x:.2f},0) rectangle ++({bw:.2f},{run * ys:.3f});")
        out.append(rf"\node[anchor=south, inner sep=1pt, font=\scriptsize\bfseries] at ({x + bw / 2:.2f},{run * ys:.3f}) {{{run:.1f}}};")
        out.append(rf"\node[anchor=north, inner sep=2pt] at ({x + bw / 2:.2f},0) {{ASR}};")
        out.append(rf"\draw[black!60] ({x0 - 0.08:.2f},0) -- ({x + bw + 0.08:.2f},0);")
        out.append(rf"\node[anchor=north, font=\scriptsize\bfseries] at ({x0 + 2.5 * (bw + gap) - gap / 2:.2f},-0.38) {{{name}}};")
    out.append(r"\end{tikzpicture}")
    write("f_waterfall", "\n".join([
        r"\begin{figure}[t]", r"\centering", COLDEFS, *out,
        rf"\caption{{FigStep's ASR (\%, primary judge) on two targets, built up from the grand mean $\mu$, its general "
        rf"strength $\alpha$, the target's susceptibility $\beta$ and its target-specific fit $\gamma$. The general "
        rf"strength is the same on both targets; the tenfold difference comes from $\beta$ and, mostly, $\gamma$.}}",
        r"\label{fig:waterfall}", r"\end{figure}", ""]))


# ---------------------------------------------------------------- judge shift
def judge_shift():
    _, _, A7 = matrix("qwen7b")
    _, _, A72 = matrix("qwen72b")
    m7, m72 = A7.mean(1), A72.mean(1)
    L = lambda v: 5.2 * (np.log10(v) - np.log10(0.8)) / (np.log10(50) - np.log10(0.8))   # cm
    order = np.argsort(-m72)
    out = [r"\begin{tikzpicture}[font=\scriptsize]"]
    H = 0.42
    for v in (1, 2, 5, 10, 20, 50):
        out.append(rf"\draw[gridc] ({L(v):.2f},-0.15) -- ({L(v):.2f},{H * len(order):.2f});")
        out.append(rf"\node[anchor=north, text=inkc] at ({L(v):.2f},-0.15) {{{v}}};")
    out.append(rf"\node[anchor=north] at ({L(6.3):.2f},-0.5) {{mean ASR over the eight targets (\%, log scale)}};")
    for r, i in enumerate(order):
        y = H * (len(order) - r - 0.5)
        m = METHODS[i]
        out.append(rf"\node[anchor=east] at (-0.1,{y:.2f}) {{{MSHORT[m]}}};")
        out.append(rf"\draw[black!35, line width=1.2pt] ({L(m7[i]):.2f},{y:.2f}) -- ({L(m72[i]):.2f},{y:.2f});")
        out.append(rf"\fill[serA] ({L(m7[i]):.2f},{y:.2f}) circle (2.2pt);")
        out.append(rf"\fill[serB] ({L(m72[i]):.2f},{y:.2f}) circle (2.2pt);")
        out.append(rf"\node[anchor=west, text=inkc] at ({L(m72[i]) + 0.1:.2f},{y:.2f}) {{${m72[i] / m7[i]:.1f}\times$}};")
    ly = H * len(order) + 0.25
    out.append(rf"\fill[serA] (0.1,{ly:.2f}) circle (2.2pt); \node[anchor=west] at (0.2,{ly:.2f}) {{Qwen2.5-7B judge}};")
    out.append(rf"\fill[serB] (2.6,{ly:.2f}) circle (2.2pt); \node[anchor=west] at (2.7,{ly:.2f}) {{Qwen2.5-72B judge}};")
    out.append(r"\end{tikzpicture}")
    write("f_judge_shift", "\n".join([
        r"\begin{figure}[t]", r"\centering", COLDEFS, *out,
        r"\caption{Mean ASR of each attack under the two Qwen judges, which share the same prompt and threshold. "
        r"The larger judge raises every attack, but by different factors, which changes the per-target ranking "
        r"(Section~\ref{sec:sensitivity}).}",
        r"\label{fig:judge_shift}", r"\end{figure}", ""]))


# ---------------------------------------------------------------- Crescendo turns
def cres_turns():
    curves = []
    for t in ORIG4:
        d6, d10 = f"results/PILOT_{t}_crescendo_pilot_seed1", f"results/K10_{t}_crescendo_pilot_seed1"
        o6, o10 = cell_outcomes(d6, "qwen7b_perturn"), cell_outcomes(d10, "qwen7b_perturn")

        def first(d):
            f = {}
            for z in load_jsonl(os.path.join(d, "rejudge_perturn_qwen7b_perturn.jsonl")):
                if (z.get("score") or 0) >= TAU:
                    f[z["request_id"]] = min(f.get(z["request_id"], 99), z["turn"])
            return f
        f6, f10 = first(d6), first(d10)
        curves.append((NAME[t], [100 * sum(v <= q for v in f6.values()) / len(o6) for q in range(1, 7)],
                       [100 * sum(v <= q for v in f10.values()) / len(o10) for q in range(1, 11)]))
    ymax = 14
    w, h, dx, dy = 2.9, 1.6, 3.5, 2.35
    out = [r"\begin{tikzpicture}[font=\scriptsize]"]
    for p, (name, c6, c10) in enumerate(curves):
        x0, y0 = (p % 2) * dx, (1 - p // 2) * dy
        X = lambda q: x0 + w * (q - 1) / 9
        Y = lambda v: y0 + h * v / ymax
        for v in (0, 5, 10):
            out.append(rf"\draw[gridc] ({x0:.2f},{Y(v):.2f}) -- ({x0 + w:.2f},{Y(v):.2f});")
            if p % 2 == 0:
                out.append(rf"\node[anchor=east, text=inkc, font=\tiny] at ({x0:.2f},{Y(v):.2f}) {{{v}}};")
        for q in (1, 6, 10):
            out.append(rf"\node[anchor=north, text=inkc, font=\tiny] at ({X(q):.2f},{y0:.2f}) {{{q}}};")
        out.append(rf"\node[anchor=south west, inner sep=1pt, font=\scriptsize\bfseries] at ({x0:.2f},{y0 + h:.2f}) {{{name}}};")
        out.append(r"\draw[serA, line width=1pt] " + " -- ".join(f"({X(q + 1):.2f},{Y(v):.2f})" for q, v in enumerate(c6)) + ";")
        out.append(r"\draw[serB, line width=1pt, densely dashed] " + " -- ".join(f"({X(q + 1):.2f},{Y(v):.2f})" for q, v in enumerate(c10)) + ";")
    out.append(rf"\node[anchor=north] at ({dx - 0.3:.2f},-0.3) {{turn}};")
    out.append(rf"\node[rotate=90, anchor=south] at (-0.45,{dy / 2 + h / 2:.2f}) {{cumulative ASR (\%)}};")
    ly = dy + h + 0.55
    out.append(rf"\draw[serA, line width=1pt] (0.3,{ly:.2f}) -- ++(0.4,0); \node[anchor=west] at (0.75,{ly:.2f}) {{$k{{=}}6$}};")
    out.append(rf"\draw[serB, line width=1pt, densely dashed] (1.7,{ly:.2f}) -- ++(0.4,0); \node[anchor=west] at (2.15,{ly:.2f}) {{$k{{=}}10$}};")
    out.append(r"\end{tikzpicture}")
    write("f_cres_turns", "\n".join([
        r"\begin{figure}[t]", r"\centering", COLDEFS, *out,
        r"\caption{Crescendo: share of requests that have succeeded by each turn (primary judge, seed 1), with a "
        r"six- and a ten-turn budget. Successes accumulate mainly in the later turns of either budget.}",
        r"\label{fig:cres_turns}", r"\end{figure}", ""]))


def main():
    table1()
    table2()
    gamma_figs()
    top1_table()
    waterfall()
    judge_shift()
    cres_turns()
    print("wrote", sorted(os.listdir(OUT)))


if __name__ == "__main__":
    main()
